document.addEventListener('DOMContentLoaded', () => {

    // ─── THEME TOGGLE ───────────────────────────────────────────────────────────
    const themeToggle = document.getElementById('theme-toggle');
    const moonIcon    = document.querySelector('.moon-icon');
    const sunIcon     = document.querySelector('.sun-icon');
    const htmlEl      = document.documentElement;

    const savedTheme      = localStorage.getItem('theme');
    const systemPrefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;

    if (savedTheme === 'light' || (!savedTheme && !systemPrefersDark)) {
        htmlEl.classList.remove('dark');
        moonIcon.classList.remove('hidden');
        sunIcon.classList.add('hidden');
    }

    themeToggle.addEventListener('click', () => {
        htmlEl.classList.toggle('dark');
        const isDark = htmlEl.classList.contains('dark');
        localStorage.setItem('theme', isDark ? 'dark' : 'light');
        moonIcon.classList.toggle('hidden', !isDark);
        sunIcon.classList.toggle('hidden', isDark);
    });

    // ─── FETCH STATUS DATA ───────────────────────────────────────────────────────
    // Reads the static status.json generated by GitHub Actions.
    // Cache-busted so GitHub CDN always serves the freshest copy.
    async function fetchStatusData() {
        try {
            const res = await fetch(`api/status.json?t=${Date.now()}`);
            if (!res.ok) throw new Error(`HTTP ${res.status}`);
            const data = await res.json();
            renderOverallStatus(data);
            renderServices(data.services);
            renderIncidents(data.incidents);
        } catch (err) {
            console.error('Failed to fetch status data:', err);
            document.getElementById('overall-message').textContent =
                'Unable to load status – please try again later.';
            document.getElementById('services-list').innerHTML =
                '<p class="error-text">Could not load service status.</p>';
            document.getElementById('incidents-list').innerHTML =
                '<p class="error-text">Could not load incident history.</p>';
        }
    }

    fetchStatusData();
    // Auto-refresh every 60 s so the page stays live
    setInterval(fetchStatusData, 60_000);

    // ─── RENDERERS ───────────────────────────────────────────────────────────────

    function renderOverallStatus(data) {
        const banner    = document.getElementById('status-banner');
        const messageEl = document.getElementById('overall-message');
        const updatedEl = document.getElementById('last-updated');

        banner.classList.remove('degraded', 'outage');

        if (data.overall_status === 'degraded' || data.overall_status === 'partial_outage') {
            banner.classList.add('degraded');
        } else if (data.overall_status === 'major_outage') {
            banner.classList.add('outage');
        }

        messageEl.textContent = data.overall_message ?? 'All Systems Operational';

        if (data.last_updated) {
            const d = new Date(data.last_updated);
            updatedEl.textContent = `Last checked: ${d.toLocaleString()}`;
        }
    }

    function renderServices(services) {
        const list = document.getElementById('services-list');
        list.innerHTML = '';

        if (!services || services.length === 0) {
            list.innerHTML = '<p class="text-secondary">No services configured.</p>';
            return;
        }

        services.forEach(service => {
            const badgeClass = service.status === 'operational'  ? 'operational'
                             : service.status === 'major_outage' ? 'outage'
                             : 'degraded';

            const badgeText = service.status.replace(/_/g, ' ');
            const uptime    = service.uptime ?? 99.9;

            const detailHtml = service.detail
                ? `<div class="service-detail ${badgeClass}">${service.detail}</div>`
                : '';

            const card = document.createElement('div');
            card.className = 'service-card';
            card.innerHTML = `
                <div class="service-header">
                    <div class="service-name">${service.name}</div>
                    <div class="badge ${badgeClass}">${badgeText}</div>
                </div>
                <div class="service-desc">${service.description}</div>
                ${detailHtml}
                <div class="uptime-bar">
                    <div class="uptime-track" title="Uptime ${uptime}%">
                        <div class="uptime-fill ${badgeClass}" style="width:${uptime}%"></div>
                    </div>
                    <div class="uptime-text">${uptime}%</div>
                </div>`;
            list.appendChild(card);
        });
    }

    function renderIncidents(incidents) {
        const list = document.getElementById('incidents-list');
        list.innerHTML = '';

        if (!incidents || incidents.length === 0) {
            list.innerHTML = '<p class="text-secondary">No recent incidents reported. ✅</p>';
            return;
        }

        incidents.forEach(incident => {
            const createdDate = new Date(incident.created_at).toLocaleDateString();

            let resolutionTimeText = 'Ongoing';
            if (incident.resolved_at) {
                const diffMs   = new Date(incident.resolved_at) - new Date(incident.created_at);
                const diffMins = Math.round(diffMs / 60_000);
                const hours    = Math.floor(diffMins / 60);
                const mins     = diffMins % 60;
                resolutionTimeText = hours > 0 ? `${hours}h ${mins}m` : `${mins}m`;
            }

            let updatesHtml = '';
            (incident.updates ?? []).forEach(update => {
                const ts = new Date(update.timestamp).toLocaleString();
                updatesHtml += `
                    <div class="timeline-event ${update.status}">
                        <div class="event-status ${update.status}">${update.status}</div>
                        <div class="event-message">${update.message}</div>
                        <div class="event-time">${ts}</div>
                    </div>`;
            });

            const card = document.createElement('div');
            card.className = 'incident-card';
            card.innerHTML = `
                <div class="incident-header">
                    <h3 class="incident-title">${incident.name}</h3>
                </div>
                <div class="incident-meta">
                    <span title="Incident Date">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                            <line x1="16" y1="2" x2="16" y2="6"></line>
                            <line x1="8" y1="2" x2="8" y2="6"></line>
                            <line x1="3" y1="10" x2="21" y2="10"></line>
                        </svg>
                        ${createdDate}
                    </span>
                    <span title="Incident Type">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <circle cx="12" cy="12" r="10"></circle>
                            <line x1="12" y1="8" x2="12" y2="12"></line>
                            <line x1="12" y1="16" x2="12.01" y2="16"></line>
                        </svg>
                        ${incident.type}
                    </span>
                    <span title="Resolution Time">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <circle cx="12" cy="12" r="10"></circle>
                            <polyline points="12 6 12 12 16 14"></polyline>
                        </svg>
                        ${resolutionTimeText}
                    </span>
                </div>
                <div class="timeline">${updatesHtml}</div>`;

            list.appendChild(card);
        });
    }
});
